# Generated by Django 6.1 on 2026-09-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tekija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(default='Tuntematon', max_length=50)),
                ('sukunimi', models.CharField(default='Tuntematon', max_length=50)),
                ('maa', models.CharField(default='Tuntematon', max_length=50)),
                ('syntymavuosi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kirja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='Nimetön', max_length=100)),
                ('genre', models.CharField(default='Yleinen', max_length=50)),
                ('julkaisuvuosi', models.IntegerField(default=0)),
                ('sivut', models.IntegerField(default=0)),
                ('tekija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tekija')),
            ],
        ),
    ]
