# Generated by Django 6.1 on 2026-09-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tekija',
            new_name='Kirjailija',
        ),
        migrations.AlterModelOptions(
            name='kirja',
            options={'verbose_name': 'Kirja', 'verbose_name_plural': 'Kirjat'},
        ),
        migrations.AlterModelOptions(
            name='kirjailija',
            options={'verbose_name': 'Kirjailija', 'verbose_name_plural': 'Kirjailijat'},
        ),
        migrations.RenameField(
            model_name='kirja',
            old_name='tekija',
            new_name='kirjailija',
        ),
    ]
