# Generated by Django 6.1 on 2026-09-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_tekija_kirjailija_alter_kirja_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lainaaja', models.CharField(default='Tuntematon', max_length=100)),
                ('lainauspaiva', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('varattu', 'Varattu'), ('lainassa', 'Lainassa'), ('palautettu', 'Palautettu')], default='varattu', max_length=20)),
                ('kirja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kirja')),
            ],
            options={
                'verbose_name': 'Laina',
                'verbose_name_plural': 'Lainat',
            },
        ),
    ]
